### ISSUE TITLE
可以请教一下数据库怎么部署的么

### ISSUE THREAD

**Issue by LiuJunQin** [liuchengyuu/carpool#3]
云开发建立了环境，上传并且部署了云函数。后面该怎么做哇，请教大佬！

**Comment by liuchengyuu** [comment]
数据库是用的云存储，微信的云能力



---原始邮件---
发件人: "LiuJunQin"<notifications@github.com&gt;
发送时间: 2020年4月13日(周一) 中午12:56
收件人: "liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [liuchengyuu/carpool] 可以请教一下数据库怎么部署的么 (#3)




 
Closed #3.

**Comment by LiuJunQin** [comment]
感谢老哥，那个问题解决了，怪我之前没好好看过云开发，项目里面 我的行程和我的收藏一直调不出来数据。可以请教一下老哥么





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuchengyuu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午12:58
收件人:&nbsp;"liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送:&nbsp;"65581134"<65581134@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [liuchengyuu/carpool] 可以请教一下数据库怎么部署的么 (#3)





 数据库是用的云存储，微信的云能力 
 
 
 
 ---原始邮件--- 
 发件人: "LiuJunQin"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月13日(周一) 中午12:56 
 收件人: "liuchengyuu/carpool"<carpool@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: Re: [liuchengyuu/carpool] 可以请教一下数据库怎么部署的么 (#3) 
 
 
 
 
   
 Closed #3.
