### ISSUE TITLE
部署以后我的行程和我的收藏一直调不出来数据！

### ISSUE THREAD

**Issue by LiuJunQin** [liuchengyuu/carpool#5]
项目里面 我的行程和我的收藏一直调不出来数据。可以请教一下老哥么

**Comment by liuchengyuu** [comment]
加我qq给你看下，2840994346



---原始邮件---
发件人: "LiuJunQin"<notifications@github.com&gt;
发送时间: 2020年4月13日(周一) 中午1:07
收件人: "liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [liuchengyuu/carpool] 部署以后我的行程和我的收藏一直调不出来数据！ (#5)




 
Closed #5.

**Comment by LiuJunQin** [comment]
好的 ，感谢大佬！
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liuchengyuu"<notifications@github.com&gt;; 
发送时间: 2020年4月13日(星期一) 中午1:12
收件人: "liuchengyuu/carpool"<carpool@noreply.github.com&gt;; 
抄送: "65581134"<65581134@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [liuchengyuu/carpool] 部署以后我的行程和我的收藏一直调不出来数据！ (#5)





 加我qq给你看下，2840994346 
 
 
 
 ---原始邮件--- 
 发件人: "LiuJunQin"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月13日(周一) 中午1:07 
 收件人: "liuchengyuu/carpool"<carpool@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: Re: [liuchengyuu/carpool] 部署以后我的行程和我的收藏一直调不出来数据！ (#5) 
 
 
 
 
   
 Closed #5.
