### ISSUE TITLE
大佬你好哇！我QQ加您了，还没有同意呢

### ISSUE THREAD

**Issue by LiuJunQin** [liuchengyuu/carpool#6]
！！

**Comment by liuchengyuu** [comment]
我没收到请求呀，&nbsp; &nbsp;qq:&nbsp; 2840994346






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiuJunQin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午1:31
收件人:&nbsp;"liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [liuchengyuu/carpool] 大佬你好哇！我QQ加您了，还没有同意呢 (#6)





 
Closed #6.

**Comment by liuchengyuu** [comment]
收藏没有数据的话，你看这个云开发--&gt; 数据库 对应的表中有数据没







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LiuJunQin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午1:31
收件人:&nbsp;"liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [liuchengyuu/carpool] 大佬你好哇！我QQ加您了，还没有同意呢 (#6)





 
Closed #6.

**Comment by LiuJunQin** [comment]
数据库对应的表中有数据呢，不知道为什么就调不出来。
大佬你的QQ名字是&nbsp; “浮生若梦”么，我发了好几次请求啦！
我QQ是：65581134&nbsp; 微信：HH850907


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liuchengyuu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 中午1:37
收件人:&nbsp;"liuchengyuu/carpool"<carpool@noreply.github.com&gt;;
抄送:&nbsp;"65581134"<65581134@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [liuchengyuu/carpool] 大佬你好哇！我QQ加您了，还没有同意呢 (#6)





 我没收到请求呀，&amp;nbsp; &amp;nbsp;qq:&amp;nbsp; 2840994346 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"LiuJunQin"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月13日(星期一) 中午1:31 
 收件人:&amp;nbsp;"liuchengyuu/carpool"<carpool@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [liuchengyuu/carpool] 大佬你好哇！我QQ加您了，还没有同意呢 (#6) 
 
 
 
 
 
   
 Closed #6.
